modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="GPL License"

[[mods]] #mandatory

modId="cwsr" #mandatory

version="3.4.0.0" #mandatory

displayName="Cyan Warrior Swords Mod" #mandatory

displayURL="https://www.curseforge.com/minecraft/mc-mods/cyan-warrior-swords-mod" #optional

logoFile="logo_mod.png" #optional

credits="This mod was updated, thanks to Raptorbk (@Raptorbk), after reading this thread on Twitter: https://bit.ly/3atx4ua. From then, he and the original author (@Juanra_Monaco_W), worked with old and new ideas for this new version." #optional

authors="Raptorbk (Main Coder); MustangXPress7 aka. Juanra_MW (Creative Design)" #optional

description='''This mod adds new swords with different habilities. You can upgrade and mix them to obtain the hability that fits you the best. You can choose between Fire, Thunder, Wind, Earth, Dark, Light, Ender and Beast! Choose the best sword for your epic battles!'''
